version: "2.3"
services:

  sub:
    privileged: true
    runtime: nvidia
    image: subscriber:dev
    tty: true
    command: [ "python3", "/app/main.py", "--ip", "0.0.0.0" ]

  pub:
    image: publisher:dev
    depends_on:
      - sub
    tty: true
    command: [ "python3", "/app/main.py", "--ip", "sub" ]
    volumes:
      - /home/dhaval/piyush/ViIDWIN/Datasets_VIDWIN/testhost:/app/video
      - /sys/fs/cgroup/memory/docker:/mem/
      - /sys/fs/cgroup/cpuacct/docker:/cpu/
    mem_limit: 3000m
    mem_reservation: 1000m
    cpu_quota: 100000