version: '2.3'
services:

  sub:
    runtime: nvidia
    image: subscriber:dev
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    networks:
      net2:
        ipv4_address: 10.5.0.5
    tty: true
    command: ["python3", "/app/main.py", "--ip", "10.5.0.5"]

networks:
  net2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1