#sub
#FROM python:3.7.1-slim
#FROM gw000/keras:2.1.4-py3-tf-cpu
FROM jihong/keras-gpu:latest-py3

MAINTAINER Piyush

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  gcc iproute wondershaper python3-pip


WORKDIR /app
COPY requirements.txt /app
COPY dnnmodel.py /app
COPY window.py /app
COPY mobilenet_model.h5 /app

RUN pip3 install -r requirements.txt

COPY main.py /app/main.py

# allow other containers/PCs to connect; maybe not necessary
EXPOSE 5551

# when using docker-compose, this command can be overwritten
CMD ["python3", "main.py", "--ip", "0.0.0.0"]
