version: '2.3'
services:

  pub:
    image: publisher:dev
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    tty: true
    command: ["python3", "/app/main.py", "--ip", "sub"]
    volumes:
      - /home/dhaval/piyush/ViIDWIN/Datasets_VIDWIN/testhost:/app/video
      #- /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup/memory/docker:/mem/
      - /sys/fs/cgroup/cpu,cpuacct/docker:/cpu/
      - /sys/fs/cgroup/pids/docker/:/pids/
      - /sys/fs/cgroup/devices/docker/:/device/
      - /proc:/host_proc/
      - /sys/fs/cgroup/cpu,cpuacct:/system_cpu/
    mem_limit: 3000m
    mem_reservation: 1000m
    cpuset: 0-1
