version: '2.3'
services:

  pub:
    runtime: nvidia
    image: publisher-cpu:dev
    build:
      context: '.'
      dockerfile: 'Dockerfile-cpu'
    tty: true
    pid: "host"
    command: ["python3", "/app/main.py", "--ip", '172.17.0.1']
    volumes:
      - /home/dhaval/piyush/ViIDWIN/Datasets_VIDWIN/Cropped Datasets for Processing:/app/video
#      - /sys/fs/cgroup/memory/docker:/mem/
      - /home/dhaval/piyush/ViIDWIN/Code/pyzmq-vidwin/stats:/docker_stats/
    environment:
      - TZ=Europe/Dublin
    mem_limit: 2000m
    mem_reservation: 1000m
    cpuset: 0-4
#    networks:
#      sub_net2:
#        ipv4_address: 10.5.0.6
#
#networks:
#  sub_net2:
#    external: true