version: '2.3'
services:

  pub:
    runtime: nvidia
    image: publisher-cpu:dev
    build:
      context: '.'
      dockerfile: 'Dockerfile-cpu'
    tty: true
    pid: "host"
    #command: ["python3", "/app/main.py", "--ip", "sub"]
    command: ["python3", "/app/main.py", "--ip", '172.17.0.1']
    volumes:
      - /home/dhaval/piyush/ViIDWIN/Datasets_VIDWIN/testhost:/app/video
      #- /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup/memory/docker:/mem/
      #- /sys/fs/cgroup/cpu,cpuacct/docker:/cpu/
      #- /sys/fs/cgroup/cpu,cpuacct:/system_cpu/
      #- /proc:/host_proc/
      - /home/dhaval/piyush/ViIDWIN/Code/pyzmq-vidwin/stats:/docker_stats/
    environment:
      - TZ=Europe/Dublin
    mem_limit: 3000m
    mem_reservation: 100m
    cpuset: 0-0
#    networks:
#      sub_net2:
#        ipv4_address: 10.5.0.6
#
#networks:
#  sub_net2:
#    external: true